config/routes.rb
MartaApp::Application.routes.draw do
  resources :selections

  get "welcome/home"
  get "welcome/radioselect" => "welcome#radioselect"
  
  get "welcome/yourbuses" => "welcome#yourbuses"

  get "welcome/busesarriving" => "welcome#yourbuses_dropdown", as: :busesarriving

  root "welcome#home"
  
  resources :stations

end

app/models/selection.rb
class Selection < ActiveRecord::Base
end

app/models/station.rb
class Station < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  bg = ['marta-img1.jpg','marta-img2.jpg','marta-img3.jpg','marta-img4.jpg']
  i = rand(0..(bg.length-1))
  @selectedBg = bg[i]

  puts "*********"
  puts @selectedBg
  puts "*********"

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :set_selection, only: [:show, :edit, :update, :destroy]

  # GET /selections
  # GET /selections.json
  def index
    @selections = Selection.all
  end

  # GET /selections/1
  # GET /selections/1.json
  def show
  end

  # GET /selections/new
  def new
    @selection = Selection.new
  end

  # GET /selections/1/edit
  def edit
  end

  # POST /selections
  # POST /selections.json
  def create
    @selection = Selection.new(selection_params)

    respond_to do |format|
      if @selection.save
        #check it out: I redirected the path below! We use the 'create' action to choose the station, and then go to this custom page...I suppose you could just as easily redesigned the Selection 'show' page. Shrug...next time!
        format.html { redirect_to busesarriving_path, notice: 'Selection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @selection }
      else
        format.html { render action: 'new' }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selections/1
  # PATCH/PUT /selections/1.json
  def update
    respond_to do |format|
      if @selection.update(selection_params)
        format.html { redirect_to @selection, notice: 'Selection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @selection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selections/1
  # DELETE /selections/1.json
  def destroy
    @selection.destroy
    respond_to do |format|
      format.html { redirect_to selections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selection
      @selection = Selection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selection_params
      params.require(:selection).permit(:station_name)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render action: 'show', status: :created, location: @station }
      else
        format.html { render action: 'new' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  #we're going to be using a method we created in the application_helper.rb. Go take a look!
  include ApplicationHelper
  
  #next two lines required to access the API:
  require 'open-uri'
  require 'json'

  #welcome/home
  #just a home/landing-page
  def home
  end

  #action/page where the user will select a station using radio buttons:
  def radioselect
    #For your ease, an array of all of the rail stations in the MARTA system.
    @stations = ["North Springs", "Hamilton E. Holmes", "Lindbergh", "Midtown", "Georgia State", "Reynoldstown/Inman Park", "Dunwoody", "Lenox", "Sandy Springs", "Medical Center", "Doraville", "Chamblee", "Brookhaven/Oglethorpe", "Arts Center", "North Avenue", "Civic Center", "Ashby", "Peachtree Center", "Vine City", "West End", "Airport", "College Park", "East Point", "Philips Arena/CNN Center", "Garnett", "West Lake", "Bankhead", "Oakland City", "Lakewood/Ft. McPherson", "King Memorial", "Avondale", "East Lake", "Kensington", "Decatur", "Indian Creek", "Edgewood/Candler Park", "Inman Park/Reynoldstown", "Buckhead"]
    #Let's save them alphabetically - will be easier to find a particular station when choosing from a list.
    @stations = @stations.sort_by{|item| item.downcase}
  end


  #page where the coming buses will be displayed, after the radio buton choice
  def yourbuses
    #the passed parameter is set to an instance variable
    @station = params[:station]
    #here we pull the real-time info from MARTA, and put it in a hash. Copy and paste the URL and get familiar with what data is in there.
    @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)

    hash_and_msg_generator(@results, @station)
    #find this method in the Application Helper!
  end

  #page where the coming buses will be displayed, after the dropdown menu choice
  def yourbuses_dropdown
    yourstation = Selection.last

    @selection = yourstation.station_name
    @results = JSON.parse(open("http://developer.itsmarta.com/BRDRestService/BRDRestService.svc/GetAllBus").read)


    hash_and_msg_generator(@results, @selection)
    #find this method in the Application Helper!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

		#this is where the User's selection - 'station' will be compared with the API data - 'results'.
		def hash_and_msg_generator(results, station)
		#we will have a couple messages to tell the user whether or not a bus is coming soon.
		@message = ""
		#we want to provide the user with the Route and Vehicle numbers for the approaching bus(es). The best way to save two related items is a hash!
		@buses = {}
		results.each do |result|
			if result["TIMEPOINT"].include? station
				#if the User's selection matching an up-coming bus stop in the API data, we will save that info in our hash
				@buses[result["ROUTE"]] = result["VEHICLE"]
				#the Route is the key and the vehicle is the value
			end
		end
		if @buses.count == 0
			#no buses have the User's station as their next stop.
			@message = "Sorry, it's gonna be a while."
		elsif @buses.count == 1
			#one bus will be making the User's station it's next stop
			@message = "A bus is on it's way!"
		elsif @buses.count > 1
			#two or more buses will be making the User's station their next stop
			@message = "These buses will be coming soon:"
		else
			#just in case we end up with a negative number somehow - who knows.
			@message = "Oops...I think there was a slight error."
		end
	end
	
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MartaApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>


<body class="homepage">
	<nav class="navbar blue-bg scroll" style="margin-bottom:-20px;" role="navigation">
		<div>
	    <ul class="nav navbar-nav">
	      <li class="active"><%= link_to "Home", root_path %></li>
	      <li><%= link_to "Choose Station (Radio Button)", welcome_radioselect_path %></li>
	      <li><%= link_to "Choose Station (Dropdown)", new_selection_path %></li>
	    </ul>
	  </div>
	</nav>

<%= yield %>

</body>


</html>

app/views/selections/_form.html.erb
<%= form_for(@selection) do |f| %>
  <% if @selection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selection.errors.count, "error") %> prohibited this selection from being saved:</h2>

      <ul>
      <% @selection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- 
    We're just gonna have one field: Select a station name! This page serves the same purpose as 'welcome/radioselect'.
  -->
  <div class="field dropdown-text">
    <!-- Below is the tag for a drop-down menu -->
    <%= f.select :station_name, Station.all.collect {|station| [ station.name ] } %>
    <!-- We will collect a list of all the Stations, passing their names, and assign whichever is chosen to the Selection's parameter 'station_name' -->
  </div>
  <div class="actions">
    <%= f.submit 'Check for buses!', :class=>'btn submit-button' %>
  </div>
<% end %>

app/views/selections/edit.html.erb
<h1>Editing selection</h1>

<%= render 'form' %>

<%= link_to 'Show', @selection %> |
<%= link_to 'Back', selections_path %>

app/views/selections/index.html.erb
<h1>Listing selections</h1>

<table>
  <thead>
    <tr>
      <th>Station name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.station_name %></td>
        <td><%= link_to 'Show', selection %></td>
        <td><%= link_to 'Edit', edit_selection_path(selection) %></td>
        <td><%= link_to 'Destroy', selection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selection', new_selection_path %>

app/views/selections/new.html.erb
<div class="scroll choose-a-station">
	<h2 class="orange-text">Choose a Station!</h2>
	<p><b>Which MARTA Station Are You At?</b></p>
</div>

<div class="dropdown">
<%= render 'form' %>
</div>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station name:</strong>
  <%= @selection.station_name %>
</p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing station</h1>

<%= render 'form' %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<h1>Listing stations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.name %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New station</h1>

<%= render 'form' %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @station.name %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>

app/views/welcome/home.html.erb
<div>
	<h2 class="orange-text">Where's the Bus?</h2>

	<div>
		<p>
			This app lets you know if you if there is a bus making its next stop at the MARTA station you are currently located at.
		</p>
		<p>
			Follow the links above to choose your station via Radio Buttons or Drop-Down Menu.
		</p>
		<p>
			To developers: note that the drop-down menu method needed the use of two databases. Here's how it works:<br />
			You, the developer, must, unfortunately, populate a database with all the MARTA stations (though there is an array of them in the 'welcome#radioselect' action). Kind of a pain. Another down-side of this method is that the user is creating a new instance of a Selection each time they go through the process. Kinda just a waste of database space - but this was the best solution I could find.
		</p>
		<p>
			To any non-ATL TTSers: sorry we could not customize this app for your town. Your public transit systems do not have the same API available. Please try to look past the possibly-unfamiliar place-names and see what the code is doing.
		</p>
	</div>
</div>

app/views/welcome/radioselect.html.erb
<div class="scroll choose-a-station">
	<h2 class="orange-text">Choose a Station!</h2>
	<p><b>Which MARTA Station Are You At?</b></p>
</div>

<div class="radios">
	<%= form_tag("/welcome/yourbuses", method: "get") do %>
		<%= label_tag(:station, " " ) %>
		<br />
		<% @stations.each do |s| %>
			<%= radio_button_tag(:station, s) %> <%= s %><br />
		<% end %>
		<%= submit_tag 'Check for buses!', :class=>'btn submit-button' %>
	<% end %>
</div>

app/views/welcome/yourbuses.html.erb
<!-- 
Here we'll see the results of the user's radio-button choice.
-->

<h3>
	You are at: <%= @station %> Station.
</h3>

<div>
	<%= @message %>
</div>
<br />
<% @buses.each do |route, vehicle| %>
	<div>
		Route: <%= route %><br />
		Vehicle: <%= vehicle %><br />
	</div>
	<hr />
<% end %>

app/views/welcome/yourbuses_dropdown.html.erb
<!-- 
This is the sister-page of yourbuses.html.erb
That one handles the results from the radio button choice,
this one handles the results from the dropdown menu choice.
-->
<h3>
	You are at: <%= @selection %> Station.
</h3>

<div>
	<%= @message %>
</div>
<br />
<% @buses.each do |route, vehicle| %>
	<div>
		Route: <%= route %><br />
		Vehicle: <%= vehicle %><br />
	</div>
	<hr />
<% end %>